name: Check API and Best Time of Task
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  check-api-and-best-time-of-task:
    runs-on: ubuntu-latest
    steps:
      - name: Get Best Time of Task
        run: |
          npm install axios
          npm start
