name: Check API and Best Time of Task
on:
    workflow_dispatch:
jobs:
  check-api-and-best-time-of-task:
    runs-on: ubuntu-latest
    steps:
      - name: Get Best Time of Task
        working-directory: ./carbonActionTrigger
        run: |
          ls
          npm install
          node index.js
